name: Build and Deploy .NET App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, gcp-demo-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and publish application
        run: |
          chmod +x build.sh
          ./build.sh
